services:
  #  redis:
  #    image: redis
  #    networks:
  #      - default
  #  postgres:
  #    image: postgres
  #    env_file:
  #      - ../.env
  #    networks:
  #      - default
  #  pgadmin:
  #    image: dpage/pgadmin4
  #    labels:
  #      - "traefik.enable=true"
  #      - "traefik.http.routers.dev-astro-pgadmin.rule=Host(`dev.astro.example.com`) && PathPrefix(`/pgadmin`)"
  #      - "traefik.http.routers.dev-astro-pgadmin.tls=true"
  #      - "traefik.http.routers.dev-astro-pgadmin.tls.certresolver=sslresolver"
  #    depends_on:
  #      - postgres
  #    env_file:
  #      - ../.env
  #    networks:
  #      - default
  #      - traefik
  #    volumes:
  #      - pgadmin-data:/var/lib/pgadmin
  web:
    build: .
    ports:
      - 4321
    restart: unless-stopped
    volumes:
      - ..:/workspace:cached
    #   depends_on:
    #     - redis
    #     - postgres
    networks:
      - traefik
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dev-astro-web.rule=Host(`dev.astro.example.com`)"
      - "traefik.http.routers.dev-astro-web.tls=true"
      - "traefik.http.routers.dev-astro-web.tls.certresolver=sslresolver"
    command: sleep infinity
    env_file:
      - ../.env
    environment:
      - TZ=Europe/Berlin
networks:
  traefik:
    external: true
#volumes:
#  pgadmin-data:
